### ISSUE TITLE
请问能否对接一下 云片的 获取回复短信？？？

### ISSUE THREAD

**Issue by djtu** [CowPanda/yunpian-sms-client#2]
首先感谢大神开发此接口，现在我这边有个小需求，需要使用 获取回复短信，希望大神能在百忙之中对接此接口，再次感谢！~~

**Comment by impanda-cookie** [comment]
已对接，请更新版本到v2.0.2 .
另外，对于没有直接对接的接口，你也可以通过自定义调用的方式实现,详见github说明:

```
smsProvider.getCustomReqSmsAPI(data,path) 

```

**Comment by djtu** [comment]
老大给力 新春快乐 万事如意
